# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 1345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1061, 641))
        self.frame.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 611, 301))
        self.calendarWidget.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"color: rgb(0, 0, 0);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(630, 70, 421, 241))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_dobav = QtWidgets.QPushButton(self.frame)
        self.pushButton_dobav.setGeometry(QtCore.QRect(940, 10, 111, 28))
        self.pushButton_dobav.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width: 1px;\n"
"border-radius: 2px}\n"
"QPushButton:hover{\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width: 3px 3px 3px 3px}")
        self.pushButton_dobav.setObjectName("pushButton_dobav")
        self.pushButton_perehod = QtWidgets.QPushButton(self.frame)
        self.pushButton_perehod.setGeometry(QtCore.QRect(940, 40, 111, 28))
        self.pushButton_perehod.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 0, 127);\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-radius: 2px;\n"
"border-width: 1px}\n"
"QPushButton:hover{\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width: 3px 3px 3px 3px}")
        self.pushButton_perehod.setObjectName("pushButton_perehod")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(634, 20, 291, 41))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 670, 1061, 641))
        self.frame_2.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 25, 91, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_perehod2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_perehod2.setGeometry(QtCore.QRect(790, 60, 93, 28))
        self.pushButton_perehod2.setObjectName("pushButton_perehod2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(140, 140, 491, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget_2 = kart(self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(530, 210, 500, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 150))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 142))
        self.widget_2.setStyleSheet("\n"
"background-color: rgb(175, 175, 175);")
        self.widget_2.setProperty("created_at", "")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(460, 120))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 50, 61, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 113, 22))
        self.lineEdit_2.setInputMask("")
        self.asdas = QtWidgets.QFormLayout()
        self.asdas.removeRow()
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 20, 231, 91))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 55, 16))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Описание"))
        self.pushButton_dobav.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_perehod.setText(_translate("MainWindow", "Перейти"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Список задач"))
        self.pushButton_perehod2.setText(_translate("MainWindow", "Переход"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cоздано "))
        self.pushButton_5.setText(_translate("MainWindow", "Del"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
from kart import kart
